import type { NextPage } from 'next';
import Head from 'next/head';
import Header from '../components/header';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>johns portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://user-images.githubusercontent.com/88212270/193459390-e4dae7e3-add5-448c-a0b5-286d808b12dc.png" />
      </Head>

      {/* HEADER */}
      <Header/>

      {/* HERO  */}


      {/* ABOUT */}


      {/* EXPERIENCE */}


      {/* SKILLS */}


      {/* PROJECTS */}


      {/* CONTACT ME */}


    </div>
  )
}

export default Home;